### ISSUE TITLE
Todo app 요구사항 명세서 작성

### ISSUE THREAD

**Issue by dobbykong** [dobbykong/Bare-Minimum#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo 내용 작성 칸
2. [ ] 추가된 Todo 내용 적용 버튼
3. [ ] Todo 내용 작성 칸 및 적용 버튼 css

### 예상 작업 시간
2h
