### ISSUE TITLE
Todo app 요구사항 명세서 작성

### ISSUE THREAD

**Issue by dobbykong** [dobbykong/Bare-Minimum#2]
### 만들고자 하는 기능이 무엇인가요?
Todo 목록 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 추가된 Todo 체크 박스 추가
2. [ ] 추가된 Todo 수정 버튼 추가
3. [ ] 추가된 Todo 삭제 버튼 추가

### 예상 작업 시간
3h
